# Generated by Django 5.1.7 on 2025-03-11 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('zip_place', models.CharField(max_length=50)),
                ('estimated_value', models.FloatField()),
                ('construction_year', models.IntegerField(max_length=4)),
                ('usable_area', models.FloatField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='portfolio.portfolio')),
            ],
        ),
    ]
