# Generated by Django 5.1.7 on 2025-03-23 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolio_name'),
        ('property', '0004_alter_property_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='estimated_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='portfolio.portfolio'),
        ),
    ]
